name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying
      run: |
        npm install
        npm run build --if-present
        cp CNAME dist
        gh-pages -d dist
